#:schema node_modules/wrangler/config-schema.json
name = "d1-tutorial"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "property"
database_id = "8b7db88a-fbdc-4518-8710-8c5a4ecce4da"

